#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFLogin
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ecomerce_StarTech")]
	public partial class DBEcomerceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    #endregion
		
		public DBEcomerceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Ecomerce_StarTechConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBEcomerceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBEcomerceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBEcomerceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBEcomerceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CambiarClave")]
		public ISingleResult<sp_CambiarClaveResult> sp_CambiarClave([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Usuario", DbType="Int")] System.Nullable<int> iD_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClaveAct", DbType="VarChar(50)")] string claveAct, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClaveNew", DbType="VarChar(50)")] string claveNew)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Usuario, claveAct, claveNew);
			return ((ISingleResult<sp_CambiarClaveResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Usuario;
		
		private System.Nullable<int> _ID_Rol;
		
		private string _CorreoElectronico;
		
		private string _Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Clave;
		
		private string _Usuario_Inserta;
		
		private System.Nullable<System.DateTime> _Fecha_Inserta;
		
		private string _Usuario_Actualiza;
		
		private System.Nullable<System.DateTime> _Fecha_Actualiza;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UsuarioChanging(int value);
    partial void OnID_UsuarioChanged();
    partial void OnID_RolChanging(System.Nullable<int> value);
    partial void OnID_RolChanged();
    partial void OnCorreoElectronicoChanging(string value);
    partial void OnCorreoElectronicoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnUsuario_InsertaChanging(string value);
    partial void OnUsuario_InsertaChanged();
    partial void OnFecha_InsertaChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_InsertaChanged();
    partial void OnUsuario_ActualizaChanging(string value);
    partial void OnUsuario_ActualizaChanged();
    partial void OnFecha_ActualizaChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_ActualizaChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					this.OnID_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Usuario = value;
					this.SendPropertyChanged("ID_Usuario");
					this.OnID_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Rol", DbType="Int")]
		public System.Nullable<int> ID_Rol
		{
			get
			{
				return this._ID_Rol;
			}
			set
			{
				if ((this._ID_Rol != value))
				{
					this.OnID_RolChanging(value);
					this.SendPropertyChanging();
					this._ID_Rol = value;
					this.SendPropertyChanged("ID_Rol");
					this.OnID_RolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="VarChar(50)")]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this.OnCorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._CorreoElectronico = value;
					this.SendPropertyChanged("CorreoElectronico");
					this.OnCorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(30)")]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Inserta", DbType="VarChar(50)")]
		public string Usuario_Inserta
		{
			get
			{
				return this._Usuario_Inserta;
			}
			set
			{
				if ((this._Usuario_Inserta != value))
				{
					this.OnUsuario_InsertaChanging(value);
					this.SendPropertyChanging();
					this._Usuario_Inserta = value;
					this.SendPropertyChanged("Usuario_Inserta");
					this.OnUsuario_InsertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Inserta", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Inserta
		{
			get
			{
				return this._Fecha_Inserta;
			}
			set
			{
				if ((this._Fecha_Inserta != value))
				{
					this.OnFecha_InsertaChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Inserta = value;
					this.SendPropertyChanged("Fecha_Inserta");
					this.OnFecha_InsertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Actualiza", DbType="VarChar(50)")]
		public string Usuario_Actualiza
		{
			get
			{
				return this._Usuario_Actualiza;
			}
			set
			{
				if ((this._Usuario_Actualiza != value))
				{
					this.OnUsuario_ActualizaChanging(value);
					this.SendPropertyChanging();
					this._Usuario_Actualiza = value;
					this.SendPropertyChanged("Usuario_Actualiza");
					this.OnUsuario_ActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Actualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Actualiza
		{
			get
			{
				return this._Fecha_Actualiza;
			}
			set
			{
				if ((this._Fecha_Actualiza != value))
				{
					this.OnFecha_ActualizaChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Actualiza = value;
					this.SendPropertyChanged("Fecha_Actualiza");
					this.OnFecha_ActualizaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_CambiarClaveResult
	{
		
		private string _Mensaje;
		
		public sp_CambiarClaveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
